version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      maven: 3.8
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests
  build:
    commands:
      - echo Build started on `date`
      - mvn package

artifacts:
  files:
    - target/*.jar
